### ISSUE TITLE
engine！= bullptr 问题

### ISSUE THREAD

**Issue by liangjunhao1998** [YuzhouPeng/unet-tensorrt#17]
![4ce613bfa5d19e53310d74ad9c04abb](https://user-images.githubusercontent.com/85820796/181202135-d527a64e-73a4-49dc-9630-6e30fc486812.jpg)
您好，我想请教一下该问题如何解决

**Comment by YuzhouPeng** [comment]
试试看用v1.0的权重，这个trt项目支持的v1.0 : https://github.com/milesial/Pytorch-UNet/releases/tag/v1.0

**Comment by liangjunhao1998** [comment]
电子工程学生会纪保部梁俊浩已收到，谢谢。祝您生活愉快！

**Comment by liangjunhao1998** [comment]
好的，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月27日(星期三) 晚上8:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YuzhouPeng/unet-tensorrt] engine！= bullptr 问题 (Issue #17)





 
试试看用v1.0的权重，这个trt项目支持的v1.0 : https://github.com/milesial/Pytorch-UNet/releases/tag/v1.0

**Comment by YuzhouPeng** [comment]
好的 感兴趣的话可以点个star

**Comment by liangjunhao1998** [comment]
您好，我想问一下有没有支持unet3.0版本的tensorrt




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuzhouPeng/unet-tensorrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 晚上8:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuzhouPeng/unet-tensorrt] engine！= bullptr 问题 (Issue #17)





 
试试看用v1.0的权重，这个trt项目支持的v1.0 : https://github.com/milesial/Pytorch-UNet/releases/tag/v1.0
