### ISSUE TITLE
可以解释一下这里up函数的参数吗？

### ISSUE THREAD

**Issue by SmallMunich** [YuzhouPeng/unet-tensorrt#3]
https://github.com/YuzhouPeng/unet-tensorrt/blob/883461d4ddfd23731ab586a70cbef9293b3c52e7/unet.cpp#L150

@YuzhouPeng 你好，我在序列化wts到trt时候，报错张量权重不匹配。我看了一下这个up函数的输入参数，resize是否代表上采样的大小，outch代表输出的channels， midch代表是中间的channels，可以解释一下为什么都是512吗？

**Comment by Wulingtian** [comment]
> https://github.com/YuzhouPeng/unet-tensorrt/blob/883461d4ddfd23731ab586a70cbef9293b3c52e7/unet.cpp#L150
> 
> @YuzhouPeng 你好，我在序列化wts到trt时候，报错张量权重不匹配。我看了一下这个up函数的输入参数，resize是否代表上采样的大小，outch代表输出的channels， midch代表是中间的channels，可以解释一下为什么都是512吗？

你那边时间推理时间多少？我这边tensorrt 量化要40多ms

**Comment by SmallMunich** [comment]
> > https://github.com/YuzhouPeng/unet-tensorrt/blob/883461d4ddfd23731ab586a70cbef9293b3c52e7/unet.cpp#L150
> > 
> > @YuzhouPeng 你好，我在序列化wts到trt时候，报错张量权重不匹配。我看了一下这个up函数的输入参数，resize是否代表上采样的大小，outch代表输出的channels， midch代表是中间的channels，可以解释一下为什么都是512吗？
> 
> 你那边时间推理时间多少？我这边tensorrt 量化要40多ms

时间差不多，我的在30~35ms   输入的1*512*512的image，不包括IO读取

**Comment by Wulingtian** [comment]
> > > https://github.com/YuzhouPeng/unet-tensorrt/blob/883461d4ddfd23731ab586a70cbef9293b3c52e7/unet.cpp#L150
> > > 
> > > @YuzhouPeng 你好，我在序列化wts到trt时候，报错张量权重不匹配。我看了一下这个up函数的输入参数，resize是否代表上采样的大小，outch代表输出的channels， midch代表是中间的channels，可以解释一下为什么都是512吗？
> > 
> > 
> > 你那边时间推理时间多少？我这边tensorrt 量化要40多ms
> 
> 时间差不多，我的在30~35ms 输入的1_512_512的image，不包括IO读取

我输入尺寸是960*640的尺寸，卡是1070

**Comment by SmallMunich** [comment]
> > > > https://github.com/YuzhouPeng/unet-tensorrt/blob/883461d4ddfd23731ab586a70cbef9293b3c52e7/unet.cpp#L150
> > > > 
> > > > @YuzhouPeng 你好，我在序列化wts到trt时候，报错张量权重不匹配。我看了一下这个up函数的输入参数，resize是否代表上采样的大小，outch代表输出的channels， midch代表是中间的channels，可以解释一下为什么都是512吗？
> > > 
> > > 
> > > 你那边时间推理时间多少？我这边tensorrt 量化要40多ms
> > 
> > 
> > 时间差不多，我的在30~35ms 输入的1_512_512的image，不包括IO读取
> 
> 我输入尺寸是960*640的尺寸，卡是1070，你是什么卡？

我的是Xavier，类比于1080ti的卡

**Comment by Wulingtian** [comment]
> > > > > https://github.com/YuzhouPeng/unet-tensorrt/blob/883461d4ddfd23731ab586a70cbef9293b3c52e7/unet.cpp#L150
> > > > > 
> > > > > @YuzhouPeng 你好，我在序列化wts到trt时候，报错张量权重不匹配。我看了一下这个up函数的输入参数，resize是否代表上采样的大小，outch代表输出的channels， midch代表是中间的channels，可以解释一下为什么都是512吗？
> > > > 
> > > > 
> > > > 你那边时间推理时间多少？我这边tensorrt 量化要40多ms
> > > 
> > > 
> > > 时间差不多，我的在30~35ms 输入的1_512_512的image，不包括IO读取
> > 
> > 
> > 我输入尺寸是960*640的尺寸，卡是1070，你是什么卡？
> 
> 我的是Xavier，类比于1080ti的卡

你是fp16还是int8？

**Comment by YuzhouPeng** [comment]
好的，我去看看

**Comment by YuzhouPeng** [comment]
在目前我只写了bilinear下采样的情况，对应的pytorch代码在这 ：https://github.com/milesial/Pytorch-UNet/blob/6aa14cbbc445672d97190fec06d5568a0a004740/unet/unet_model.py#L19
同时pytorch代码中，unet_parts.py中上采样对于bilinear的处理是这样的：
https://github.com/milesial/Pytorch-UNet/blob/6aa14cbbc445672d97190fec06d5568a0a004740/unet/unet_parts.py#L53
所以这就是为什么都是512.

**Comment by YuzhouPeng** [comment]
当然在tensorRT中用反卷积替代bilinear是有问题的，后续会改进
