### ISSUE TITLE
模型的结果和tensorrt的结果不一致

### ISSUE THREAD

**Issue by hejun888** [YuzhouPeng/unet-tensorrt#6]
你好，我用的是你们unet项目，然而分割结果有些不一样，左边是模型分割的结果，右边是转成tensorrt后的推理结果，想问下为何结果是不一致的，可能是什么原因造成的。谢谢
 
![K 756 DSUD@NFIE 3953%4S](https://user-images.githubusercontent.com/28728850/117249391-1368b280-ae74-11eb-9f30-5a95c1ca8a3b.png)

**Comment by YuzhouPeng** [comment]
目前upsample部分使用的是deconv，会导致一些问题，后续会抽空修改结构

**Comment by YuzhouPeng** [comment]
我刚刚更新了下代码 修改了upsample的部分
I have just updated code and modified upsample part
分割显示结果如下：
results as following:
原图：
original img:
![000149_326](https://user-images.githubusercontent.com/13601004/117414291-8abc4600-af49-11eb-95ae-2dc16ccac64f.jpg)
分割结果:
seg result:
![s_000149_326 bmp_unet](https://user-images.githubusercontent.com/13601004/117414428-b4756d00-af49-11eb-86f6-93fd7cfa9a93.jpg)

you can pull new code and try results

**Comment by YuzhouPeng** [comment]
@hejun888

**Comment by hejun888** [comment]
OK，it's work now, thank you very much!
